### ISSUE TITLE
Spawn little blobs

### ISSUE THREAD

**Issue by kingstone426** [coherence/showcase-blobs#74]

**Comment by tadej** [comment]
@kingstone426 we need to tweak this a bit. A very small player should not spawn blobs almost half its size. Perhaps only blobs with radious > N spawn these?

**Comment by kingstone426** [comment]
Agreed. We now also have a problem with small blobs spawned exceeding the 10k drifter limit. We might want to count "small drifters" separately from "normal drifters".

**Comment by tadej** [comment]
We could also just keep the 10k limit higher .... respawn dead drifters if total count is <10k, but always spawn child blobs.

The frequency of child blobs could easily also be 5x lower than currently.

**Comment by kingstone426** [comment]
I can decrease the child blob frequency, but even with 1/5 rate the child blobs will cause the total drifter count to rise steadily and since normal drifters only spawn at <10k there will be fewer and fewer normal drifters with time.

**Comment by kingstone426** [comment]
Nevermind, 1/5 spawn rate actually makes spawning small blobs less frequent than eating normal blobs so the balance seems to be restored.

**Comment by tadej** [comment]
Perfect .. if this starts to go awry, we could also relax the 10k limit ... but in general, the smallest blobs should be eaten with time anyway.
